services:
  pg:
    image: postgres:latest
    container_name: users-pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users
  redis:
    image: redis:alpine
    container_name: users-redis
    restart: always
    ports:
      - 6379:6379
  nats:
    image: nats:alpine
    container_name: users-nats
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
      - 4244:4244
      - 8244:8244
