build: 
	go build -o ./bin/app ./cmd/main.go

run:
	go run ./cmd/main.go

test:
	go test -cover ./...

docker-build:
	docker build -t mhiri/chronobreak:latest .

docker-run:
	docker run -it --rm -p 8080:8080 mhiri/chronobreak:latest

compose-up:
	docker-compose up -d

compose-down:
	docker-compose down

clean:
	rm -rf ./bin

proto:
	protoc \
		--go_out=. \
		--go_opt=paths=source_relative \
		--go-grpc_out=. \
		--go-grpc_opt=paths=source_relative \
		./proto/users/v1/users.proto
	gofr wrap grpc server -proto=./proto/users/v1/users.proto
	mv ./proto/users/v1/*.go ./internal/api/users/
